### ISSUE TITLE
Navigation between Jenkins and Ontrack

### ISSUE THREAD

**Issue by Pinio31** [jenkinsci/ontrack-plugin#49]
I'm not able to easily navigate from specific Jenkins build/job to any ontrack dashboards. For my perspective ideally user should have navigated button on side-panel in Jenkins

**Comment by dcoraboeuf** [comment]
@Pinio31, what do you think about the following?

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1206964/52806118-79e13a80-3088-11e9-8bd2-f0cff3de932b.png">

**Comment by dcoraboeuf** [comment]
Note that I cannot put this in the BlueOcean layout.

**Comment by Pinio31** [comment]
Very nice, it will definitely improve navigation

**Comment by dcoraboeuf** [comment]
Available in version 3.2
