### ISSUE TITLE
Use correct graphql query in graphql example.

### ISSUE THREAD

**Issue by npirotte** [jenkinsci/ontrack-plugin#58]
In https://github.com/jenkinsci/ontrack-plugin/blob/master/PIPELINE.md#ontrack-graphql-step example is 

```
ontrackGraphQL(script: '{projects{name}}')
```

It's unclear if the graphql query should be

```
query {
  foo { bar }
}
```

Or `foo { bar }`

Example should be changed to 
```
ontrackGraphQL(script: 'query { { projects { name } } }')
```

**Comment by dcoraboeuf** [comment]
Fixed by #60
